# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.13.1
_src_path: gh:algorandfoundation/algokit-beaker-default-template
author_email: violetas123321@gmail.com
author_name: vixx16
contract_name: tic_tac_toe_single_player
deployment_language: python
preset_name: starter
project_name: XOFullStack-contracts

